### ISSUE TITLE
Wrong Width and Height in Rotation Manager 

### ISSUE THREAD

**Issue by SanjayRathor** [changsanjiang/SJOrentationObserver#1]
Hi ,
It's a wonder full lib. I am using this in my project. But there is a issue . It is giving wrong width and hight on orientation change in landscape mode. In iphone 6 

                CGFloat width = [UIScreen mainScreen].bounds.size.width;  //337 
                CGFloat height = [UIScreen mainScreen].bounds.size.height; //667 

                CGFloat max = MAX(width, height);
                CGFloat min = MIN(width, height);
                self.target.bounds = (CGRect){CGPointZero, (CGSize){max, min}};
                self.target.center = (CGPoint){min * 0.5, max * 0.5};

**Comment by changsanjiang** [comment]
Hello, @SanjayRathor.
can you try the following code?
```Objective-C
                CGFloat width = window.bounds.size.width;
                CGFloat height = window.bounds.size.height;
                CGFloat max = MAX(width, height);
                CGFloat min = MIN(width, height);
                self.target.bounds = (CGRect){CGPointZero, (CGSize){max, min}};
                self.target.center = (CGPoint){min * 0.5, max * 0.5};
```

**Comment by SanjayRathor** [comment]
Now it showing correct. But my viewCOntroller's view is giving opposite frames. It is showing width 337 in landscape mode.  I think it is due to navigation and view controllers  category .
Can you tell me what is going wrong

**Comment by changsanjiang** [comment]
Yes  <img width="1040" alt="screen shot 2018-08-06 at 5 02 32 pm" src="https://user-images.githubusercontent.com/25744224/43707427-a192fc24-999a-11e8-8ca2-3ae68cbf2372.png">

The following code is to allow the controller to rotate.
```Objective-C
- (BOOL)shouldAutorotate {
    return YES;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskAllButUpsideDown;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return UIInterfaceOrientationPortrait;
}
```

**Comment by changsanjiang** [comment]
What do you want to do in viewController when fullscreen?

**Comment by SanjayRathor** [comment]
Hi ,
I want to add subview in centre when player is in full screen . Brightness view sound views, labels  etc . 
and these will be center aligned

**Comment by changsanjiang** [comment]
These subviews can be added to the view of the player , it can rotate with the player.

**Comment by changsanjiang** [comment]
The method in this screenshot is the delegate method of RotationManager, you can hide or show subviews according to your own needs.
![image](https://user-images.githubusercontent.com/25744224/43710562-93ae6e7e-99a2-11e8-9452-bc1586aa60af.png)

**Comment by SanjayRathor** [comment]
Thanks. I am using this method. In this method I m setting the frames of my subviews but inside this method when i am using self.view.frames  . then i am getting the wrong frames .

**Comment by SanjayRathor** [comment]
Thanks a lot for your support. I am using the auto layout. But due to wrong frame size  subviews are showing according to portrait mode

**Comment by changsanjiang** [comment]
My facebook name is [SanJiang Change](https://www.facebook.com/sanjiang.chang.3), we can chat here.

**Comment by changsanjiang** [comment]
Or.  Do you have TeamViewer?

**Comment by SanjayRathor** [comment]
I have send you the friend request on Facebook
