### ISSUE TITLE
使用这个类一定要设置superview和target吗？

### ISSUE THREAD

**Issue by HZRZCW** [changsanjiang/SJOrentationObserver#6]
_mgr = [[SJVCRotationManager alloc] initWithViewController:self];
    _mgr.superview = self.view;
    _mgr.target = self.view;
    _mgr.rotationCondition = ^BOOL(id<SJRotationManagerProtocol>  _Nonnull mgr) {
        return YES;
    };
    _mgr.delegate = self;

如果不设置就没有效果

**Comment by changsanjiang** [comment]
更新一下吧, 最新版的可以不用设置了.
